# Changes here will be overwritten by Copier
_commit: cf81ff6
_src_path: gh:34j/pypackage-template
add_me_as_contributor: false
copyright_year: '2024'
documentation: true
email: 34j.95a2p@simplelogin.com
full_name: 34j
github_username: 34j
has_cli: false
initial_commit: true
open_source_license: MIT
open_with_vscode: true
package_name: quaternion_unity
project_name: Quaternion Unity
project_short_description: Unity-like and NumPy-compatible quaternion
project_slug: quaternion-unity
run_poetry_install: true
setup_github: true
setup_pre_commit: true
setup_venv: true
venv_version: '3.11'

